config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end

  devise_for :users, path: '',
    path_names: {
      registration: 'register'
    },
    controllers: {
      registrations: 'registrations'
    },
    defaults: {format: :json}

  root 'welcome#index'
  post '/login' => 'login#create'
  get '/admin' => 'admin#index'

  get 'events/index'
  post 'events/index'
  get 'events/create_event'
  post 'events/create_event'
  get 'events/show'
  post 'events/show'

  namespace :api, except: [:new, :edit] do
    namespace :v1 do
      resources :users, except: [:create]
      resources :email, only: [:create]
      resources :events do
        get '/summary' => 'events#summary'
        resource :guest_referrals, path: :refer, only: [:show, :create]
        resources :guests do
          member do
            get :invite
            get :checkin
            patch :book
            resource :tickets
          end
        end
        resources :email_templates, path: :templates
        resources :referral_rewards, path: :rewards
        resources :referral_summary, only: [:index]
        resources :seats
      end
    end
  end
  
  resources :events do
    resource :refer
    resource :book
    resources :guests
    resources :seating_types
  end

  

  post '/import_new_spreadsheet' => 'events#import_new_spreadsheet'
  post '/open_existed_spreadsheet'  => 'events#open_existed_spreadsheet', as: :open_existed_spreadsheet
  post '/seat_categories'  => 'events#seat_categories'
  post '/reconcile'  => 'events#reconcile'
  post '/create_referral' => 'events#create_referral', as: :create_referral
  
  get '/events/:event_id/guests/:id/send' => 'guests#send_email_invitation', as: :send_event_guest
  put '/events/:event_id/guests/:id/update_in_place' => 'guests#update_in_place', as: :update_event_guest
  
  

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :guests, dependent: :destroy
    has_many :seats, dependent: :destroy
    has_many :referral_rewards, dependent: :destroy
    has_many :email_templates, dependent: :destroy
    has_one_attached :image, dependent: :purge_later
    has_one_attached :box_office, dependent: :purge_later

    validates :title, presence: true
    validates :address, presence: true
    validates :datetime, presence: true, expiration: true
    validate :validate_image
    validate :validate_box_office
    
    private

    def validate_image
      return unless image.attached?
      return if image.blob.content_type.start_with? 'image/'
      errors.add(:image, 'needs to be an image')
    end

    def validate_box_office
      return unless box_office.attached?
      content_types = ['csv', 'tsv', 'xlsx', 'xlsm', 'ods'].map { |ext| Rack::Mime.mime_type ".#{ext}" }
      return if box_office.blob.content_type.start_with? *content_types
      errors.add(:box_office, 'needs to be ods, xlsx, xlsm, csv, or tsv')
    end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::ApiController
  def index
    render json: {message: 'No bearer token'}, status: :forbidden and return unless current_user
    events = Event.where(user_id: current_user.id).limit(params[:limit]).offset(params[:offset])
    render json: events.map{ |event|
      with_attachments(event)
    }
  end

  def show
    @event = Event.find(params[:id])
    render json: {event: @event}
  end

  def create
    render json: {message: 'No bearer token'}, status: :forbidden and return unless current_user
    par = event_params.to_h
    par[:user_id] = current_user.id
    event = Event.create(par)
    render_valid(event)
    if event.valid?
      event.save
      create_default_templates(event)
      render json: with_attachments(event)
    else
      render json: {errors: event.errors.full_messages}, status: :unprocessable_entity
    end
  end

  def update
    event = Event.find params[:id]
    update_referral_count event
    event.update(event_params)
    if event.valid?
      event.save
      render json: with_attachments(event)
    else
      render json: {errors: event.errors.full_messages}, status: :unprocessable_entity
    end
  end

  def destroy
    event = Event.find params[:id]

    if params.has_key? :image
      event.image.purge if event.image.attached?
    end

    if params.has_key? :box_office
      event.box_office.purge if event.box_office.attached?
    end

    unless params.has_key? :partial
      unless event.destroy
        render json: event.errors, status: :unprocessable_entity
        return
      end
    end

    head :ok
  end

  def summary
    res = Seat.left_joins(:guest_seat_tickets, :guests)
              .select('seats.category,price,total_count,'\
                      'sum(coalesce(committed,0)) as total_committed,'\
                      'sum(coalesce(allotted,0)) as total_allotted,'\
                      'total_count - sum(coalesce(committed,0)) as remaining,'\
                      'count(*) filter(where "booked") as total_booked,'\
                      'count(*) filter (where not "booked") as total_not_booked,'\
                      'count(distinct(guest_id)) as total_guests,'\
                      'sum(coalesce(committed,0)) * price as balance')
              .group('seats.id')
              .where(seats: {event_id: params[:event_id]})
    render json: res, except: [:id]
  end

  private

  def with_attachments(model)
    image_url = url_for(model.image) if model.image.attached?
    box_office_url = url_for(model.box_office) if model.box_office.attached?
    model.as_json.merge({ image_url: image_url, box_office_url: box_office_url })
  end

  def update_referral_count(event)
    # updates the referral count after updating the box office data by looking for
    # the referred email
    return unless event_params.has_key? :box_office
    prior_emails = event.box_office.open do |file|
      sheet = Roo::Spreadsheet.open(file.path)
      sheet.each(email: 'Email').map { |row| row[:email] }.uniq
    end

    # todo: better to check if files have same content first?
    sheet = Roo::Spreadsheet.open(event_params[:box_office].tempfile.path)
    curr_emails = sheet.each(email: 'Email').map { |row| row[:email] }.uniq
    new_emails = prior_emails.nil? ? curr_emails : curr_emails - prior_emails
    return if new_emails.empty?

    converted_referrals = GuestReferral.select('guest_id, count(guest_id)')
                                       .where(email: new_emails, counted: false)
                                       .group(:guest_id)
    converted_referrals.each { |converted_referral|
      count = converted_referral.count
      guest = converted_referral.guest
      guest.guest_referral_rewards.update_all("count = count + #{count}")
    }
    GuestReferral.where(email: new_emails).update(counted: true)
  end

  def create_default_templates(event)
    rsvp_template = EmailTemplate.new 
    rsvp_template.name = 'RSVP Invitation'
    rsvp_template.subject = '{{event.title}} - Invitation'
    rsvp_template.body = File.read(Rails.root.join('app', 'views', 'guest_mailer', 'rsvp_invitation_email.html'))
    rsvp_template.is_html = true
    rsvp_template.event_id = event.id
    rsvp_template.user_id = current_user.id

    confirmation_template = EmailTemplate.new 
    confirmation_template.name = 'RSVP Confirmation'
    confirmation_template.subject = '{{event.title}} - Confirmation'
    confirmation_template.body = File.read(Rails.root.join('app', 'views', 'guest_mailer', 'rsvp_confirmation_email.html'))
    confirmation_template.is_html = true
    confirmation_template.event_id = event.id
    confirmation_template.user_id = current_user.id
    
    rsvp_template.save
    confirmation_template.save
  end

  def event_params
    params.permit(:title, :address, :datetime, :image, :description, :box_office, :last_modified, :user_id)
        #:image, :box_office, :x1, :y1, :x2, :y2, :user_id)
  end

  def render_valid(event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    #@events = Event.all
    @events = Event.where(user_id: 64) # hardcoded needs to be as some type of param
  end

  def show
    @event = Event.find(params[:id])
    @event_id = params[:id]
    @seats = Seat.where(event_id: params[:id])
    @guests = Guest.where(event_id: params[:id])
    @res = Seat.left_joins(:guest_seat_tickets, :guests)
              .select('seats.category,price,total_count,'\
                      'sum(coalesce(committed,0)) as total_committed,'\
                      'sum(coalesce(allotted,0)) as total_allotted,'\
                      'total_count - sum(coalesce(committed,0)) as remaining,'\
                      'count(*) filter(where "booked") as total_booked,'\
                      'count(*) filter (where not "booked") as total_not_booked,'\
                      'count(distinct(guest_id)) as total_guests,'\
                      'sum(coalesce(committed,0)) * price as balance')
              .group('seats.id')
              .where(seats: {event_id: @event.id})
  end

  def new
    @event = Event.new
  end

  def create
    par = event_params.to_h
    if doorkeeper_token
      par[:user_id] = doorkeeper_token[:resource_owner_id]
    else
      par[:user_id] = warden.authenticate(scope: :public)
    end
    @event = Event.new(par)

    #render json: {event: event}
    if @event.save
      redirect_to @event
    end
    #render_valid(event)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  def import_new_spreadsheet
    if !params[:file]
      redirect_to root_path
    end
    
    @event = Event.import(params[:file])
    redirect_to @event
  end

  def summary
    res = GuestSeatTicket.joins(:seat, :guest)
              .select('category,price,total_count,'\
                      'sum(committed) as total_committed,'\
                      'sum(allotted) as total_allotted,'\
                      'total_count - sum(committed) as remaining,'\
                      'count(*) filter(where "booked") as total_booked,'\
                      'count(*) filter (where not "booked") as total_not_booked,'\
                      'count(distinct(guest_id)) as total_guests,'\
                      'sum(committed) * price as balance')
              .group('seats.id')
              .where(seats: {event_id: params[:event_id]})
    render json: res.to_json, except: [:id]
  end

  private
  def event_params
    params.permit(:title, :address, :datetime, :image, :description, :last_modified, :box_office, :user_id, :token)
  end

  def render_valid(event)
    @event = event
    if event.valid?
      event.image.attach(params[:image]) if params[:image].present?
      event.box_office.attach(params[:image]) if params[:box_office].present?
      #head :ok
      #render json: {event: event, params: params}
      params[:id] = event.id
      @event
    else
      render json: {errors: event.errors.full_messages}, status: :unprocessable_entity
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_email_modal.html.erb
<div data-controller='email dynamic' data-email-eventid-value=<%= @event_id %> data-action='email:emailed->dynamic#reload'>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#email-modal" data-action='email#queryTemplates'>
    Email
  </button>
  <div class='modal fade' id='email-modal' tabindex='-1' aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Send Email</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id='form-email' data-email-target='email'>
            <select class='form-select mb-2' name='template_id'
                data-email-target='select' data-action='change->email#loadTemplate'>
              <option value=''>Generic</option>
            </select>
            <input type='hidden' type='number' name='event_id' value=<%= @event_id %>>
            <div class='form-floating mb-2'>
              <input class='form-control' id='email-from' type='email' name='senders[]'>
              <label for='email-from'>From</label>
            </div>
            <div class='form-floating mb-2'>
              <input class='form-control' id='email-to' type='email' name='recipients[]'>
              <label for='email-to'>To</label>
            </div>
            <div class='form-floating mb-2'>
              <input class='form-control' id='email-subject' type='text' name='subject' data-email-target='subject'>
              <label for='email-subject'>Subject</label>
            </div>
            <div class='form-floating'>
              <textarea id='email-body' class='form-control h-100' name='body' data-email-target='body'></textarea>
              <label for='email-body'>Body</label>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" type='submit' form='form-email'
              data-bs-dismiss="modal" data-action='email#sendEmail'>Send</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<form method='post' action='/events/show'>
    <input type='number' id='user_id' name='user_id'>
    <input type='text' id='title' name='title'>
    <input type='text' id='address' name='address'>
    <input type='text' id='description' name='description'>
    <input type='datetime-local' id='datetime', name='datetime'>
    <input type="hidden" id="last_modified" name="last_modified" value= <%= Time.now %> >
    <input type='submit'>
</form>

<!-- Not really new but needs to go away from show.html.erb -->
<h3>Summarized Ticket Commitments Information</h3>

<div class="table-responsive">
<table class="table table-sm col-md-12">
  <thead class="thead-light">
    <tr> 
      <th>Seat Category</th>
      <th>Total Seats</th>
      <th>Total Box Office Commitments</th>
      <th>Total Guest Commitments</th>
      <th>Balance</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <!--<tr>-->
    <!-- <td><%= @event.seat_category %></td> -->
    <!-- <td><%= best_in_place [@event], :total_seats, :as => :input, :place_holder => "#{@event.total_seats}", :url => event_path(@event) %></td>-->
    <!--   <td><%= @event.total_seats_box_office %></td>-->
    <!--   <td><%= @event.total_seats_guest %></td>-->
    <!--   <td><%= @event.balance %></td>-->
    <!-- </tr>-->
  <!--  <% @total_seat_wise_split.each do |row| %>
      <tr>
        <td><%= row.seat_category %></td>
        <td><%= row.total_seats %></td>
        <td><%= row.vip_seats %></td>
        <td><%= row.non_vip_seats %></td>
        <td><%= row.balance %></td>
      </tr>
      
    <% end %>
    -->
    
    <% @seat_type_split.each do |row| %>
      <tr>
        <td><%= row.seat_category %></td>
        <td><%= row.total_seat_count %></td>
        <td><%= row.box_office_seat_count %></td>
        <td><%= row.vip_seat_count %></td>
        <td><%= row.balance_seats %></td>
        <td><%= link_to 'Edit', edit_seating_type_path(row) %></td>
        <td><%= link_to 'Delete', row, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    <tr>

    <!-- <%= form_tag("/seating_types/") %>
      <td><%= text_field_tag :"seating_type" %></td>
      <td><%= text_field_tag :"total_seat_count" %></td>
      <td><%= submit_tag("Add") %></td>
    </form>
    -->
    <td>  
          
    </tr>
  </tbody>
</table>



</div>

<div style="text-align: center;">
<%= link_to 'New Seating Type', new_seating_type_path, class:"btn btn-primary" %> <br> <br>


<br><br>
</div>


<h3> Guest List </h3>

<div class="table-responsive">
<table class="table table-sm col-md-12">
  <thead class="thead-light">
    <tr>
      <% @guest_params.each do |param| %>
        <% column_title = param.dup.gsub('_', ' ')%>
        <% column_title.capitalize! %>
        <th><%= column_title %></th>
      <% end %>
      <th>Action</th>
      <!--<th>Ticket Booking Status</th>-->
      <!--<th>Total Booked</th>-->
    </tr>
  </thead>
  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <% @guest_params.each do |param| %>
          <td>
            <%= best_in_place [@event, guest], param, :as => :input, :place_holder => "#{guest[param]}", 
              :url => update_event_guest_path(@event, guest) %>
          </td>
        <% end %>
        <td>
          <%= link_to "Send",  send_event_guest_path(@event, guest)%>
          <%= link_to "Delete", [@event, guest], method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
        <!--<td>-->
        <!--  <%= guest.booking_status %>-->
        <!--</td>-->
        <!--<td>-->
        <!--  <%= guest.total_booked_num %>-->
        <!--</td>-->
      </tr>
    <% end %>
    <tr>
      <%= form_for [@event, @event.guests.build] do |form| %>
      <!--<%= form_for [@event, @event.guests.build],  :url => update_event_guest_path(@event) do |form| %>-->
        <% @guest_params.each do |param| %>  
        <% if param=="event_id" %>  
          <td> 
            <%= form.hidden_field :"#{param}" , value: @event.id %>
          </td>
        <% else %>
          <td> 
            <%= form.text_field :"#{param}" %>
          </td>
        <% end %>
        <% end %>
        <td><%= submit_tag("Add") %></td>
      <% end %>
      
      <!--<% (0..1).each do |i| %>     -->
      <!--  <td></td>-->
      <!--<% end %>-->
    </tr>
  </tbody>
</table>
</div>

<%= form_tag reconcile_path %>
<br>
<%= link_to "Reconcile", event_path(:reconcile => 'true', :id => @event.id), class:"btn btn-primary" %>

<h3><br>Box Office List</h3>
<div class="table-responsive">
<table class="table table-sm" id="events">
<thead class="thead-light">
  <tr>
    <% @customers[0].each do |column_name| %>
      <th><%= column_name %></th>
    <% end %>
  </tr>
</thead>
<tbody>
  <% @customers[1..-1].each do |row| %>
    <tr>
      <% row.each do |cell| %>
        <td>
          <%= cell %>
        </td>
      <% end %>
    </tr>
  <% end %>
</tbody>
</table>
</div>
</section>
</body>
<%end%>

app/views/events/show.html.erb
<% content_for :nav do %>
  <%= render 'layouts/nav' %>
<% end %>

<style>
    body {
    
      //background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(https://www.teahub.io/photos/full/197-1977791_portland-wallpapers-hd-portland-oregon-city-view.jpg);
      background-repeat: no-repeat; 
      background-position: center;
      background-attachment: fixed; 
      webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      height:100%;
      width:100%; 
      
    }

    section{
      padding: 40px;
      padding-bottom: 100vh;
      background-color: white;
    }

  h3{
  text-align: center;
  }

  #referral-button {
    -webkit-appearance: button;
    -moz-appearance: button;
    appearance: button;
    padding: 20px;
    font-size: 20px;
    text-decoration: none;
    color: white;
    background-color: black;
  }

  .level-contents-toggle{
    text-align: center;
  }

  #referral-contents-toggle{
    display: none; 
    text-align: center; 
    padding-top: 10px; 
    padding-bottom: 20px; 
    background-color: #e6ccff;
    color: black; 
    border-radius: 10px;
    padding: 10px;
  }

  #guest-list-table{
    display: none;
  }
  table, th, td {
    border: 1px solid black;
  }
  th, td {
    padding: 5px;
    #width: 209.8px;
  }

  th.value input{
    width: 100%
  }
</style>

<script>
//JS toggles RSVP Form visibility
  function toggle_referral() {
  var button_name = document.getElementById("referral-prepper");
  var x = document.getElementById("referral-contents-toggle");
  if (button_name.innerHTML == "Open Referral Reward Template") {
    button_name.innerHTML = "Close Referral Reward Template";
    x.style.display = "block";
  } else {
    button_name.innerHTML = "Open Referral Reward Template";
    button_name.style.background = "lightgreen";
    x.style.display = "none";
  }
}

  function guest_table_toggle() {
    var button_name = document.getElementById("guest-list-table-toggle");
    var x = document.getElementById("guest-list-table");
    if(button_name.innerHTML == "Guest-List Table") {
      button_name.innerHTML = "Close Guest-List Table";
      x.style.display = "block";
    } else {
      button_name.innerHTML = "Guest-List Table";
      x.style.display = "none";
    }
  }

  function referral_table_toggle() {
    var button_name = document.getElementById("referral-table-toggle");
    var x = document.getElementById("referral-table");
    if(button_name.innerHTML == "Referral Table") {
      button_name.innerHTML = "Close Referral Table";
      x.style.display = "block";
    } else {
      button_name.innerHTML = "Referral Table";
      x.style.display = "none";
    }
  }

  function seating_table_toggle() {
  var button_name = document.getElementById("seating-table-toggle");
  var x = document.getElementById("seating-table");
  if(button_name.innerHTML == "Seating Levels") {
    button_name.innerHTML = "Close Seating Levels";
    x.style.display = "block";
  } else {
    button_name.innerHTML = "Seating Levels";
    x.style.display = "none";
  }
}

function refresh() {
  // or $('#myform')[0] with jQuery
  $("#reward-msg").load(location.href + " #reward-msg");
  
}
</script>

<h1><%= @event.title %></h1>
<div id='event-summary' class='mb-4'>
  <div class='d-flex justify-content-start'>
    <% if @event.image.attached? %>
    <img class='w-25 me-2' src='<%= url_for(@event.image) %>' alt='Event image'>
    <% end %>

    <div>
      <p>Event Date: <%=@event.datetime %></p> <!-- format this to look nicer -->
      <p>Address: <%=@event.address %></p> <!-- <p><b>Event Address: 1255 NW 9th Ave, Portland, OR 97209</b></p> Example of what addr should look like--> 
      <p>Description: <%=@event.description %></p>
    </div>

    <div data-controller='update dynamic' data-update-url-value='/api/v1/events' data-action='update:updated->dynamic#reload'>
      <%= render 'form' %>
    </div>
  </div>
  <div class='d-flex mt-2'>
    <button class='btn btn-primary me-2' data-bs-toggle="modal" data-bs-target="#event-modal">Edit Event</button>
    <%= button_to "Delete Event", @event, :method => :delete, data: {confirm: "Are you sure you want to delete this event?"}, class: 'btn btn-danger' %>
  </div>
</div>

<script>
var eventModal = document.getElementById('event-modal')
var updateButton = eventModal.querySelector('button[type="submit"]')
eventModal.addEventListener('show.bs.modal', function (event) {
  var button = event.relatedTarget
  eventModal.querySelector('.modal-title').textContent = "Update Event"
  eventModal.querySelector('button[type="submit"]').textContent = "Update"
  eventModal.querySelector('input[data-nxt-id]').setAttribute('data-nxt-id', "<%= @event.id %>")
  eventModal.querySelector('input[data-nxt-id]').value = "<%= @event.id %>"
  eventModal.querySelector('#event-name').value = "<%= @event.title %>"
  eventModal.querySelector('#event-address').value = "<%= @event.address %>"
  eventModal.querySelector('#event-description').value = "<%= @event.description %>"
  eventModal.querySelector('#event-datetime').value = (new Date("<%= @event.datetime.to_fs(:iso8601) %>")).toISOString().slice(0,16)
})
</script>

<h2>Manage Seating Levels</h2>
<div id="seating-table" class='mb-4'>
  <table class="center">
  <thead>
    <th width=199.8>Category</th>
    <th width=199.8>Total Count</th>
  </thead>
  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <th width="199.8"><%= seat.category %></th>
        <th width="199.8"><%= seat.total_count %></th>
      </tr>
    <% end %>
  </tbody>
  </table>
  <div>
    <form id='form-seat' class='mb-2' method="post" action="/events/<%= @event.id %>/seating_types">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <table>
        <tr>
          <th>
            <input type="text" name="category">
          </th>
          <th>
            <input type="number" name="total_count">
          </th>
        </tr>
      </table>
    </form>
    <button type="submit" value="submit" form='form-seat' class="btn btn-primary">Create Seating Type</button>
  </div>
</div>

<h4> Seating Summary Information </h4>
<div id='seating-summary' class='mb-4'>
  <table class="center">
    <tr>
      <th width=199.8>Category</th>
      <th width=199.8>Total Committed</th>
      <th width=199.8>Total Allotted</th>
      <th width=199.8>Remaining</th>
      <th width=199.8>Total Booked</th>
      <th width=199.8>Total Guests</th>
      <th width=199.8>Balance</th>
    </tr>
    <tbody>
      <% @res.each do |result| %>
        <tr>
          <th width=199.8><%= result.category %></th>
          <th width=199.8><%= result.total_committed %></th>
          <th width=199.8><%= result.total_allotted%></th>
          <th width=199.8><%= result.remaining %></th>
          <th width=199.8><%= result.total_booked %></th>
          <th width=199.8><%= result.total_guests %></th>
          <th width=199.8><%= result.balance %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- button to edit/add guests -->

<h2>Manage Guests</h2>
<div class='mb-4'>
  <div class='d-flex justify-content-between'>
    <div class='d-flex'>
      <%= render 'email_template' %>
      <span class='ms-2 me-2'></span>
      <%= render 'email_modal' %>
    </div>
    <div>
      <a href='/api/v1/events/<%= @event_id %>/guests?download'><button class='btn btn-primary'>Export Guest List</button></a>
    </div>
  </div>
  <%= render 'guest_list' %>
</div>

<h2>Manage Referrals</h2>
<%= render 'referral_table' %>

<script>
var emailModal = document.getElementById('email-modal')
emailModal.addEventListener('show.bs.modal', function (event) {
  var button = event.relatedTarget
  var recipient = button.getAttribute('data-nxt-email')
  var modalInput = emailModal.querySelector('#email-to')
  modalInput.value = recipient
})
</script>

<!--<div id="form-div">
<h3>Import Box Office Data</h3>
<%= form_tag import_new_spreadsheet_path, multipart: true  do %> 
  <div style="text-align: center;">
    <br>
    <%= label_tag(:file, "Accepted types: .xlsx") %><br>
    <%= file_field_tag(:file, :id => "file-button", required: true) %><br><br>
    <%= submit_tag("Import Latest Box Office Data", :class => "button") %>
  </div>
<% end %>
</div> -->

<h4 class="display-10" style="text-align: center; color: gray;"> Referral Rewards </h1><br><br>
<div id="referral">
  <div style="text-align: center;" id="center-referral-button">
    <button type="button" id="referral-prepper" class="btn btn-success btn-rounded" onclick="toggle_referral()">Open Referral Reward Template</button>
  </div>
  <br><br>
  <div id="referral-contents-toggle">
  <h4>Referral Reward Email Template</h4>
  <div class="referral-template" style="background: white; color: black;"> 
        <p>Hi Guest,</p>
        <p id="reward-msg">Please send your friend an invitation to FashionNXT by inserting their email in the box below. You will receive <%= $reward.to_s %> Reward if any of your friends purchase tickets to FashionNXT.</p>
        <p id="email"><b>Email:  <%= label_tag(:email, "")%>
        <%= text_field_tag(:email, nil, :required => 'true', placeholder: "email", style:"color: black;")%><br><br></p>
        <p>Choose the date you are going and want your friends to join:</p>
        <p id="event-date"><b>Event date:  <%= label_tag(:event_date, "") %>
        <%= text_field_tag(:event_date, nil, :required => 'true', placeholder: "MM/DD/YYYY", style:"color: black;")%><br><br></p>
  </div>

    <%= form_tag '/events/create_event', :id => "referral-form", :remote => true do %>
    <%= label_tag(:reward, "Insert Reward:", :style => "color: black;") %>
    <%= text_field_tag(:reward, nil, :required => 'true', placeholder: "XYZ Reward", :style => "color: black;")%><br><br>
    <%= submit_tag "Save Changes", :id => "thisone", :class => "btn btn-success btn-rounded" %>
    <% end %>
       
      <br>
        <%= button_tag "Preview Changes", :id => "thisone", :type => "button", :class => "btn btn-success btn-rounded", :onclick => "refresh()" %>
      <br>



    <!--<br><%= button_to "Back to Dashboard", root_path, :class => "btn btn-success btn-rounded", :type => "button", :method => "get" %>-->

</div>

<%= link_to "Back", '/events', class:"btn btn-primary" %><br><br> <!-- question if/what this should change to -->