config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end

  devise_for :users, path: '',
    path_names: {
      registration: 'register'
    },
    controllers: {
      registrations: 'registrations'
    },
    defaults: {format: :json}

  root 'welcome#index'
  post '/login' => 'login#create'
  get '/admin' => 'admin#index'

  get 'events/index'
  post 'events/index'
  get 'events/create_event'
  post 'events/create_event'
  get 'events/show'
  post 'events/show'

  namespace :api, except: [:new, :edit] do
    namespace :v1 do
      resources :users, except: [:create]
      resources :email, only: [:create]
      resources :events do
        get '/summary' => 'events#summary'
        resource :guest_referrals, path: :refer, only: [:show, :create]
        resources :guests do
          member do
            get :invite
            get :checkin
            patch :book
            resource :tickets
          end
        end
        resources :email_templates, path: :templates
        resources :referral_rewards, path: :rewards
        resources :referral_summary, only: [:index]
        resources :seats
      end
    end
  end
  
  resources :events do
    resource :refer
    resource :book
    resources :guests
    resources :seating_types
  end

  

  post '/import_new_spreadsheet' => 'events#import_new_spreadsheet'
  post '/open_existed_spreadsheet'  => 'events#open_existed_spreadsheet', as: :open_existed_spreadsheet
  post '/seat_categories'  => 'events#seat_categories'
  post '/reconcile'  => 'events#reconcile'
  post '/create_referral' => 'events#create_referral', as: :create_referral
  
  get '/events/:event_id/guests/:id/send' => 'guests#send_email_invitation', as: :send_event_guest
  put '/events/:event_id/guests/:id/update_in_place' => 'guests#update_in_place', as: :update_event_guest
  
  

end

app/controllers/seating_types_controller.rb
class SeatingTypesController < ApplicationController
  before_action :set_seating_type, only: %i[ show edit update destroy ]

  # GET /seating_types or /seating_types.json
  def index
    @seating_types = Seat.all
  end

  # GET /seating_types/1 or /seating_types/1.json
  def show
  end

  # GET /seating_types/new
  def new
    @seating_type = Seat.new
  end

  # GET /seating_types/1/edit
  def edit
  end

  # POST /seating_types or /seating_types.json
  def create
    #render json: {params: seating_type_params}
    @seating_type = Seat.new(seating_type_params)
    @seating_type.price = 21
    #render json: {seating_type: seating_type}
    #@seating_type.event_id = 1
    #@seating_type.balance_seats=@seating_type.total_seat_count - @seating_type.vip_seat_count - @seating_type.box_office_seat_count

    #respond_to do |format|
    if @seating_type.save
      #format.html { redirect_to @seating_type, notice: "Seating type created !" }
      #format.json { render :show, status: :created, location: @seating_type }
      redirect_to event_path(@seating_type.event_id)
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @seating_type.errors, status: :unprocessable_entity }
    end
    #end
  end

  # PATCH/PUT /seating_types/1 or /seating_types/1.json
  def update
    rem_seats = seating_type_params[:total_seat_count].to_i - seating_type_params[:vip_seat_count].to_i - seating_type_params[:box_office_seat_count].to_i
    respond_to do |format|
      if @seating_type.update(seating_type_params)
        @seating_type.update({:balance_seats => rem_seats})
        format.html { redirect_to @seating_type, notice: "Seating type was successfully updated." }
        format.json { render :show, status: :ok, location: @seating_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seating_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seating_types/1 or /seating_types/1.json
  def destroy
    @event_ref = @seating_type.event.id
    @seating_type.destroy
    respond_to do |format|
      format.html { redirect_to @seating_type, notice: "Seating type was successfully destroyed.", flash: {event_ref: @event_ref} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seating_type
      @seating_type = Seat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seating_type_params
      #params.require(:seating_type).permit(:seat_category, :total_seat_count, :vip_seat_count, :box_office_seat_count, :balance_seats, :event_id)
      params.permit(:category, :total_count, :event_id, :price)
    end
end

app/views/seating_types/_form.html.erb
<form method="post" action="/events/<%= params[:event_id] %>/seating_types">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="field form-group">
    <label>Seat Category</label>
    <input type="text" name="category">
  </div>
  <div class="field form-group">
    <label>Total seat count</label>
    <input type="number" name="total_count">
  </div>
  <button type="submit" value="submit" class="button">Create Seating Type</button>
</form>

app/views/seating_types/edit.html.erb
<h1>Editing Seating Type</h1>

<%= render 'form', seating_type: @seating_type %>

<%= link_to 'Show', @seating_type %> |
<%= link_to 'Back', event_path %>

app/views/seating_types/index.html.erb
<h1>Seating Types</h1>

<table class="table">
  <thead>
    <tr>
      <th>Seat category</th>
      <th>Total seat count</th>
      <th>Vip seat count</th>
      <th>Box office seat count</th>
      <th>Balance seats</th>
      <!--<th>Event</th>-->
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @seating_types.each do |seating_type| %>
      <tr>
        <td><%= seating_type.seat_category %></td>
        <td><%= seating_type.total_count %></td>
        <!--<td><%= seating_type.event %></td>-->
        <td><%= link_to 'Show', seating_type %></td>
        <td><%= link_to 'Edit', edit_seating_type_path(seating_type) %></td>
        <td><%= link_to 'Delete', seating_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seating Type', new_seating_type_path %> |
<% if @seating_types.length() != 0 %>
 <%= link_to 'Back', event_path(@seating_types[0].event.id) %>
<% else %>
  <%= link_to 'Back', event_path(flash[:event_ref]) %>
<% end %>

app/views/seating_types/new.html.erb
<h1>New Seating Type</h1>

<%= render 'form', seating_type: @seating_type %>

app/views/seating_types/show.html.erb
<div class="jumbotron">

<p>
  <strong>Seat category:</strong>
  <%= @seating_type.category %>
</p>

<p>
  <strong>Total seat count:</strong>
  <%= @seating_type.total_count %>
</p>

<p>
  <strong>Balance seats:</strong>
  <%= @seating_type.price %>
</p>

<p>
  <strong>Event:</strong>
  <%= @seating_type.event.title %>
</p>

<%= link_to 'Edit', edit_event_seating_type_path(@seating_type), class:"btn btn-secondary" %> |
<%= link_to 'Back', event_path(@seating_type.event_id), class:"btn btn-secondary" %>
</div>