config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
  end

  devise_for :users, path: '',
    path_names: {
      registration: 'register'
    },
    controllers: {
      registrations: 'registrations'
    },
    defaults: {format: :json}

  root 'welcome#index'
  post '/login' => 'login#create'
  get '/admin' => 'admin#index'

  get 'events/index'
  post 'events/index'
  get 'events/create_event'
  post 'events/create_event'
  get 'events/show'
  post 'events/show'

  namespace :api, except: [:new, :edit] do
    namespace :v1 do
      resources :users, except: [:create]
      resources :email, only: [:create]
      resources :events do
        get '/summary' => 'events#summary'
        resource :guest_referrals, path: :refer, only: [:show, :create]
        resources :guests do
          member do
            get :invite
            get :checkin
            patch :book
            resource :tickets
          end
        end
        resources :email_templates, path: :templates
        resources :referral_rewards, path: :rewards
        resources :referral_summary, only: [:index]
        resources :seats
      end
    end
  end
  
  resources :events do
    resource :refer
    resource :book
    resources :guests
    resources :seating_types
  end

  

  post '/import_new_spreadsheet' => 'events#import_new_spreadsheet'
  post '/open_existed_spreadsheet'  => 'events#open_existed_spreadsheet', as: :open_existed_spreadsheet
  post '/seat_categories'  => 'events#seat_categories'
  post '/reconcile'  => 'events#reconcile'
  post '/create_referral' => 'events#create_referral', as: :create_referral
  
  get '/events/:event_id/guests/:id/send' => 'guests#send_email_invitation', as: :send_event_guest
  put '/events/:event_id/guests/:id/update_in_place' => 'guests#update_in_place', as: :update_event_guest
  
  

end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/_nav.erb
<div class="collapse navbar-collapse" id="navbarTogglerDemo01" data-controller='nav'>
  <%= link_to "Dashboard" , events_path, class: "nav-link"%>
</div>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EVENTNXT</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_importmap_tags %>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD15UtHa0mICshgHLTfDPXj8IUCpTCB7MY&libraries=places&callback=initMap" data-turbolinks-eval="false"></script> <!-- GMAP API -->
  <script>window.process = { env: {} }</script>
</head>
<body>
  <iframe name="dummyframe" id="dummyframe" style="display: none;"></iframe>

  <nav class="nav navbar navbar-expand-lg navbar-light justify-content-between" style="background-color: #e6ccff;">
    <h1 class="title">EVENTNXT</h1>
    <%= yield :nav %>
  </nav>

  
  <main class='d-flex m-auto flex-column w-75'>
    <%# Render "flash" messages in our application. This loads _flash.erb %>
    <%# <%= render 'layouts/flash' %>
    <%= yield %>
  </main>
</body>
</html>